import { MissionPeriod, MissionRarity } from '@prisma/client';

export interface MissionCatalogSeed {
  code: string;
  title: string;
  description: string;
  period: MissionPeriod | null;
  theme: string;
  iconKey: string | null;
  exclusionGroup: string | null;
  rarity: MissionRarity;
  starReward: number;
  crystalReward: number;
  isActive: boolean;
  displayOrder: number;
}

const rewardFor = (period: MissionPeriod | null) => {
  if (period === MissionPeriod.DAILY) return { starReward: 1, crystalReward: 0 };
  if (period === MissionPeriod.WEEKLY) return { starReward: 3, crystalReward: 1 };
  if (period === MissionPeriod.MONTHLY) return { starReward: 7, crystalReward: 5 };
  return { starReward: 0, crystalReward: 0 };
};

const legacy = (
  number: number,
  title: string,
  description: string,
  period: MissionPeriod,
  theme: string,
  exclusionGroup: string | null = null,
): MissionCatalogSeed => ({
  code: `legacy_${String(number).padStart(3, '0')}`,
  title,
  description,
  period,
  theme,
  iconKey: null,
  exclusionGroup,
  rarity: MissionRarity.NORMAL,
  isActive: true,
  displayOrder: number,
  ...rewardFor(period),
});

const current = (
  code: string,
  title: string,
  description: string,
  period: MissionPeriod,
  iconKey: string,
  displayOrder: number,
  exclusionGroup: string | null = null,
): MissionCatalogSeed => ({
  code,
  title,
  description,
  period,
  theme: 'PupiMundo',
  iconKey,
  exclusionGroup,
  rarity: MissionRarity.NORMAL,
  isActive: true,
  displayOrder,
  ...rewardFor(period),
});

export const missionCatalog: MissionCatalogSeed[] = [
  legacy(
    1,
    'Como está seu coração?',
    'Escolha a emoção que representa como você está se sentindo hoje.',
    MissionPeriod.DAILY,
    'Emoções',
  ),
  legacy(2, 'Meu sorriso', 'Conte algo que fez você sorrir hoje.', MissionPeriod.DAILY, 'Emoções'),
  legacy(
    3,
    'Desenhe sua emoção',
    'Faça um desenho mostrando sua emoção.',
    MissionPeriod.WEEKLY,
    'Emoções',
  ),
  legacy(
    4,
    'Respire antes',
    'Respire cinco vezes antes de responder.',
    MissionPeriod.DAILY,
    'Emoções',
  ),
  legacy(
    5,
    'Conte seu dia',
    'Conte para um adulto como foi seu dia.',
    MissionPeriod.DAILY,
    'Emoções',
  ),
  legacy(
    6,
    'Escolha uma carinha',
    'Toque na carinha que representa sua emoção.',
    MissionPeriod.DAILY,
    'Emoções',
  ),
  legacy(
    7,
    'Minha qualidade',
    'Diga uma qualidade que você tem.',
    MissionPeriod.MONTHLY,
    'Emoções',
  ),
  legacy(8, 'Obrigado!', 'Agradeça por uma coisa boa do seu dia.', MissionPeriod.DAILY, 'Emoções'),
  legacy(
    9,
    'Orgulho de mim',
    'Conte algo que conseguiu fazer sozinho.',
    MissionPeriod.MONTHLY,
    'Emoções',
  ),
  legacy(
    10,
    'Abraço de emoção',
    'Dê um abraço em alguém que você gosta.',
    MissionPeriod.DAILY,
    'Emoções',
  ),
  legacy(
    11,
    'Respire com o Pupi',
    'Respire lentamente acompanhando o Pupi.',
    MissionPeriod.DAILY,
    'Calma',
  ),
  legacy(12, 'Olhos fechados', 'Feche os olhos por 30 segundos.', MissionPeriod.DAILY, 'Calma'),
  legacy(13, 'Lugar tranquilo', 'Encontre um lugar calmo da casa.', MissionPeriod.MONTHLY, 'Calma'),
  legacy(
    14,
    'Bolinha sensorial',
    'Use sua bolinha sensorial por um minuto.',
    MissionPeriod.DAILY,
    'Calma',
  ),
  legacy(15, 'Música calma', 'Ouça uma música relaxante.', MissionPeriod.DAILY, 'Calma'),
  legacy(
    16,
    'Experimente algo novo',
    'Experimente um alimento ou atividade diferente.',
    MissionPeriod.MONTHLY,
    'Coragem',
    'NEW_EXPERIENCE',
  ),
  legacy(17, 'Peça ajuda', 'Peça ajuda quando precisar.', MissionPeriod.WEEKLY, 'Coragem'),
  legacy(18, 'Tente novamente', 'Não desista de um desafio.', MissionPeriod.WEEKLY, 'Coragem'),
  legacy(
    19,
    'Fale com alguém',
    'Converse com uma pessoa nova.',
    MissionPeriod.MONTHLY,
    'Coragem',
    'NEW_SOCIAL_CONNECTION',
  ),
  legacy(20, 'Pequeno desafio', 'Faça algo que parecia difícil.', MissionPeriod.MONTHLY, 'Coragem'),
  legacy(
    21,
    'Escove os dentes',
    'Escove seus dentes sozinho.',
    MissionPeriod.DAILY,
    'Autonomia',
    'ORAL_HYGIENE',
  ),
  legacy(
    22,
    'Guarde brinquedos',
    'Guarde pelo menos três brinquedos.',
    MissionPeriod.DAILY,
    'Autonomia',
    'TOY_ORGANIZATION',
  ),
  legacy(23, 'Arrume a cama', 'Organize sua cama.', MissionPeriod.DAILY, 'Autonomia', 'BED_MAKING'),
  legacy(24, 'Vista-se sozinho', 'Coloque sua roupa sozinho.', MissionPeriod.DAILY, 'Autonomia'),
  legacy(25, 'Guarde os sapatos', 'Organize seus sapatos.', MissionPeriod.DAILY, 'Autonomia'),
  legacy(26, 'Leve o prato', 'Leve seu prato até a pia.', MissionPeriod.DAILY, 'Autonomia'),
  legacy(
    27,
    'Organize a mochila',
    'Confira e organize sua mochila.',
    MissionPeriod.WEEKLY,
    'Autonomia',
  ),
  legacy(28, 'Lave as mãos', 'Lave corretamente as mãos.', MissionPeriod.DAILY, 'Autonomia'),
  legacy(29, 'Faça um elogio', 'Elogie um amigo ou familiar.', MissionPeriod.WEEKLY, 'Amizade'),
  legacy(30, 'Compartilhe', 'Empreste um brinquedo.', MissionPeriod.MONTHLY, 'Amizade'),
  legacy(31, 'Ajude alguém', 'Ofereça ajuda para alguém.', MissionPeriod.MONTHLY, 'Amizade'),
  legacy(32, 'Diga obrigado', 'Agradeça uma gentileza.', MissionPeriod.DAILY, 'Amizade'),
  legacy(33, 'Faça sorrir', 'Faça alguém sorrir hoje.', MissionPeriod.MONTHLY, 'Amizade'),
  legacy(
    34,
    'Abraço especial',
    'Dê um abraço em alguém da família.',
    MissionPeriod.DAILY,
    'Família',
  ),
  legacy(
    35,
    'Leia junto',
    'Leia um livro com um adulto.',
    MissionPeriod.WEEKLY,
    'Família',
    'READING',
  ),
  legacy(36, 'Converse', 'Conte como foi seu dia.', MissionPeriod.DAILY, 'Família'),
  legacy(37, 'Ajude em casa', 'Ajude em uma tarefa simples.', MissionPeriod.WEEKLY, 'Família'),
  legacy(38, 'Eu te amo', "Diga 'eu te amo' para alguém.", MissionPeriod.DAILY, 'Família'),
  legacy(39, 'Olhe o céu', 'Observe o céu por um minuto.', MissionPeriod.DAILY, 'Natureza'),
  legacy(40, 'Encontre uma flor', 'Procure uma flor ou planta.', MissionPeriod.MONTHLY, 'Natureza'),
  legacy(41, 'Ouça os pássaros', 'Escute os sons da natureza.', MissionPeriod.WEEKLY, 'Natureza'),
  legacy(
    42,
    'Faça um desenho',
    'Desenhe algo que você gosta.',
    MissionPeriod.WEEKLY,
    'Criatividade',
  ),
  legacy(43, 'Massinha', 'Modele um animal com massinha.', MissionPeriod.MONTHLY, 'Criatividade'),
  legacy(
    44,
    'Conte uma história',
    'Invente uma pequena história.',
    MissionPeriod.MONTHLY,
    'Criatividade',
  ),
  legacy(45, 'Construa', 'Monte algo usando blocos.', MissionPeriod.MONTHLY, 'Criatividade'),
  legacy(46, 'Conte até 20', 'Conte em voz alta até vinte.', MissionPeriod.DAILY, 'Aprendizagem'),
  legacy(
    47,
    'Procure a letra A',
    'Encontre a letra A em um livro.',
    MissionPeriod.WEEKLY,
    'Aprendizagem',
  ),
  legacy(48, 'Quebra-cabeça', 'Monte um quebra-cabeça.', MissionPeriod.WEEKLY, 'Aprendizagem'),
  legacy(49, 'Dance', 'Dance por um minuto.', MissionPeriod.DAILY, 'Movimento'),
  legacy(50, 'Pule', 'Faça dez pulos.', MissionPeriod.DAILY, 'Movimento'),
  current(
    'daily_bright_smile',
    'Sorriso brilhante',
    'Escove os dentes.',
    MissionPeriod.DAILY,
    'BRIGHT_SMILE',
    101,
    'ORAL_HYGIENE',
  ),
  current(
    'daily_tidy_bed',
    'Cama arrumada',
    'Arrume sua cama.',
    MissionPeriod.DAILY,
    'TIDY_BED',
    102,
    'BED_MAKING',
  ),
  current(
    'daily_toys_in_place',
    'Tudo no lugar',
    'Guarde seus brinquedos.',
    MissionPeriod.DAILY,
    'TOYS_IN_PLACE',
    103,
    'TOY_ORGANIZATION',
  ),
  current(
    'weekly_reading_time',
    'Hora da leitura',
    'Leia um livro ou leia junto com alguém.',
    MissionPeriod.WEEKLY,
    'READING',
    104,
    'READING',
  ),
  current(
    'weekly_body_in_motion',
    'Corpo em movimento',
    'Pratique um esporte ou atividade física.',
    MissionPeriod.WEEKLY,
    'MOVEMENT',
    105,
  ),
  current(
    'weekly_new_story',
    'Uma história nova',
    'Assista a um filme ou história que você ainda não conhecia.',
    MissionPeriod.WEEKLY,
    'NEW_STORY',
    106,
  ),
  current(
    'monthly_something_different',
    'Algo diferente',
    'Experimente uma atividade ou esporte novo.',
    MissionPeriod.MONTHLY,
    'TRY_SOMETHING',
    107,
    'NEW_EXPERIENCE',
  ),
  current(
    'monthly_new_interest',
    'Novo interesse',
    'Descubra algo que você gostaria de fazer como hobby.',
    MissionPeriod.MONTHLY,
    'NEW_INTEREST',
    108,
  ),
  current(
    'monthly_new_connection',
    'Uma nova conexão',
    'Converse ou brinque com alguém novo, se você se sentir confortável.',
    MissionPeriod.MONTHLY,
    'NEW_CONNECTION',
    109,
    'NEW_SOCIAL_CONNECTION',
  ),
  {
    code: 'rare_lost_crystal',
    title: 'Cristal Perdido',
    description: 'Ajude o Pupi a encontrar um cristal escondido. Recompensa bônus.',
    period: null,
    theme: 'Missões Raras',
    iconKey: null,
    exclusionGroup: null,
    rarity: MissionRarity.RARE,
    starReward: 0,
    crystalReward: 0,
    isActive: false,
    displayOrder: 201,
  },
  {
    code: 'rare_ziggo_mission',
    title: 'Missão do Ziggo',
    description: 'Ajude Ziggo a controlar uma emoção e ganhe um prêmio especial.',
    period: null,
    theme: 'Missões Raras',
    iconKey: null,
    exclusionGroup: null,
    rarity: MissionRarity.RARE,
    starReward: 0,
    crystalReward: 0,
    isActive: false,
    displayOrder: 202,
  },
  {
    code: 'rare_lupy_visit',
    title: 'Visita do Lupy',
    description: 'Lupy aparece com um desafio divertido e inesperado.',
    period: null,
    theme: 'Missões Raras',
    iconKey: null,
    exclusionGroup: null,
    rarity: MissionRarity.RARE,
    starReward: 0,
    crystalReward: 0,
    isActive: false,
    displayOrder: 203,
  },
  {
    code: 'rare_mystery_chest',
    title: 'Baú Misterioso',
    description: 'Complete uma missão surpresa para abrir um baú especial.',
    period: null,
    theme: 'Missões Raras',
    iconKey: null,
    exclusionGroup: null,
    rarity: MissionRarity.RARE,
    starReward: 0,
    crystalReward: 0,
    isActive: false,
    displayOrder: 204,
  },
  {
    code: 'rare_guardian_of_the_day',
    title: 'Guardião do Dia',
    description: 'Conclua um desafio exclusivo e receba uma medalha rara.',
    period: null,
    theme: 'Missões Raras',
    iconKey: null,
    exclusionGroup: null,
    rarity: MissionRarity.RARE,
    starReward: 0,
    crystalReward: 0,
    isActive: false,
    displayOrder: 205,
  },
];

export const normalMissionCatalog = missionCatalog.filter(
  (mission) => mission.rarity === MissionRarity.NORMAL,
);
export const rareMissionCatalog = missionCatalog.filter(
  (mission) => mission.rarity === MissionRarity.RARE,
);
