import { Transform } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsISO8601, IsNotEmpty, IsOptional, IsString, IsUUID, MaxLength } from 'class-validator';

export const FAMILY_NOTE_MAX_LENGTH = 2000;

export class FamilyNotesQueryDto {
  @ApiPropertyOptional({ type: String, format: 'date-time', description: 'Inclusive lower bound' })
  @IsOptional()
  @IsISO8601({ strict: true })
  from?: string;

  @ApiPropertyOptional({ type: String, format: 'date-time', description: 'Exclusive upper bound' })
  @IsOptional()
  @IsISO8601({ strict: true })
  to?: string;
}

export class CreateFamilyNoteDto {
  @ApiProperty({ maxLength: FAMILY_NOTE_MAX_LENGTH })
  @Transform(({ value }: { value: unknown }) => (typeof value === 'string' ? value.trim() : value))
  @IsString()
  @IsNotEmpty()
  @MaxLength(FAMILY_NOTE_MAX_LENGTH)
  text!: string;

  @ApiProperty({ format: 'uuid', description: 'Stable idempotency key generated by the client' })
  @IsUUID()
  clientRequestId!: string;

  @ApiPropertyOptional({
    type: String,
    format: 'date-time',
    description: 'Defaults to the current time',
  })
  @IsOptional()
  @IsISO8601({ strict: true })
  observedAt?: string;
}

export class UpdateFamilyNoteDto {
  @ApiProperty({ maxLength: FAMILY_NOTE_MAX_LENGTH })
  @Transform(({ value }: { value: unknown }) => (typeof value === 'string' ? value.trim() : value))
  @IsString()
  @IsNotEmpty()
  @MaxLength(FAMILY_NOTE_MAX_LENGTH)
  text!: string;
}

export class ChildFamilyNotesParamDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID()
  childId!: string;
}

export class ChildFamilyNoteParamDto extends ChildFamilyNotesParamDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID()
  noteId!: string;
}

export class FamilyNoteDto {
  @ApiProperty({ format: 'uuid' })
  id!: string;

  @ApiProperty({ format: 'uuid' })
  childId!: string;

  @ApiProperty()
  text!: string;

  @ApiProperty({ type: String, format: 'date-time' })
  observedAt!: Date;

  @ApiProperty({ type: String, format: 'date-time' })
  createdAt!: Date;

  @ApiProperty({ type: String, format: 'date-time' })
  updatedAt!: Date;
}
